apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eventrouter.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "get"
  - "list"
- nonResourceURLs:
  - "*"
  verbs:
  - "get"
  - "list"
