apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventrouter.fullname" . }}
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
data:
  EVENT_ROUTER_DEBUG: "{{ .Values.env.EVENT_ROUTER_DEBUG }}"
  EVENT_ROUTER_INSECURE: "{{ .Values.env.EVENT_ROUTER_INSECURE }}"
  EVENT_ROUTER_RESYNC_INTERVAL: "{{ .Values.env.EVENT_ROUTER_RESYNC_INTERVAL }}"
  EVENT_ROUTER_THROTTLE_PERIOD: "{{ .Values.env.EVENT_ROUTER_THROTTLE_PERIOD }}"
  EVENT_ROUTER_NAMESPACE:  "{{ .Values.env.EVENTSSE_GET_LIMIT | default .Release.Namespace }}"
  EVENT_ROUTER_QUEUE_MAX_CAPACITY: "{{ .Values.env.EVENT_ROUTER_QUEUE_MAX_CAPACITY }}"
  EVENT_ROUTER_QUEUE_WORKER_THREADS:  "{{ .Values.env.EVENT_ROUTER_QUEUE_WORKER_THREADS }}"
