apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventrouter.fullname" . }}
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
data:
  EVENT_ROUTER_NAMESPACE:  "{{ .Release.Namespace }}"
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}